pub mod sunshine;
pub mod capture;
pub mod encoder;
pub mod moonlight;
pub mod audio;
pub mod optimization;
pub mod health_server;
pub mod zero_copy;
pub mod simd_ops;
pub mod rtp_optimization;
pub mod lock_free;
pub mod memory_optimization;
pub mod error_recovery;
pub mod production_monitoring;
pub mod compiler_optimization;
pub mod advanced_networking;

pub use moonlight::{MoonlightServer, ServerConfig};
pub use health_server::HealthServer;
pub use zero_copy::{VideoBufferPool, ZeroCopyVideoBuffer, PoolConfig};
pub use simd_ops::{SIMDVideoProcessor, CPUCapabilities};
pub use rtp_optimization::{SIMDRtpProcessor, FastRtpPacket, RtpPacketBatch};
pub use lock_free::{LockFreeSessionRegistry, LockFreeRingBuffer, LockFreeMemoryPool};
pub use memory_optimization::{StreamingAllocator, VideoFrameHandle, AudioBufferHandle, PacketHandle};
pub use error_recovery::{ErrorRecoverySystem, ErrorContext, CircuitBreaker};
pub use production_monitoring::{ProductionMonitoringSystem, ApplicationMetrics, HealthCheck};
pub use compiler_optimization::{CompilerOptimizationSystem, ProfileGuidedOptimizer, BoltOptimizer, CompilerFlagOptimizer};
pub use advanced_networking::{AdvancedNetworkingSystem, IoUringSystem, RdmaSystem, PacketProcessor};