apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"
      manageAlerts: true
      prometheusType: "Prometheus"
      prometheusVersion: "2.40.0"
      cacheLevel: "High"
      incrementalQuerying: true
      incrementalQueryOverlapWindow: "10m"
      disableRecordingRules: false
      customQueryParameters: ""
      exemplarTraceIdDestinations:
        - name: "trace_id"
          datasourceUid: "jaeger"